name: 'gitlab-metrics'
description: 'Gets the gitlab metrics and makes a json file from it'
inputs:
  path:
    description: "The path of the file to write"
    required: true
outputs:
  size:
    description: 'The returned size'
runs:
  using: 'node12'
  main: 'dist/index.js'
