name: 'gitlab-metrics'
description: 'Gets the gitlab metrics and makes a json file from it'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
